// A1 acceptance evidence for the local simulation; not live provider/security acceptance.
const {chromium}=require('playwright-core'),{createServer}=require('./serve.cjs');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const out='preview/admin-a1';fs.mkdirSync(out,{recursive:true});const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 const result={routes:[],captures:[],checks:[],errors:[]};
 try{
  browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),base=`http://127.0.0.1:${server.address().port}/admin/index.html`;
  page.on('pageerror',e=>result.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)result.errors.push(r.status()+' '+r.url());});page.on('request',r=>{if(r.method()!=='GET'||!r.url().startsWith(`http://127.0.0.1:${server.address().port}/`))result.errors.push('Unexpected request '+r.method()+' '+r.url());});
  const go=async route=>{await page.goto(base+'#'+route);await page.waitForFunction(()=>document.querySelector('h1'));};
  const state=()=>page.evaluate(()=>AdminStore.state);
  const confirm=async name=>{await page.locator('dialog').getByRole('button',{name,exact:true}).click();};
  const action=async (name)=>page.getByRole('button',{name,exact:true}).click();
  const reset=async n=>{await page.evaluate(n=>{AdminStore.reset(n||0);AdminUI.render();},n);};
  await go('orders');await page.evaluate(()=>{localStorage.setItem('public-cart-sentinel','unchanged');sessionStorage.setItem('public-session-sentinel','unchanged');});
  const routes=await page.evaluate(()=>Object.keys(AdminUI.screens));
  for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:900});for(const route of routes){await go(route);assert(!['Record unavailable','Page not found'].includes(await page.locator('h1').innerText()),route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Overflow '+width+' '+route);result.routes.push({width,route});if([390,1440].includes(width)&&['orders','orders/record','orders/packing','orders/refund','products','products/artwork','support/case','reports/sales','settings/readiness','settings/journeys','tools'].includes(route)){const filename=`${out}/${route.replaceAll('/','-')}-${width}.png`;await page.screenshot({path:filename,fullPage:true});result.captures.push(filename);}}}
  result.checks.push('All registered Admin screens at 360, 390, 768 and 1440 px; no document overflow, missing records or JS/network errors.');
  await page.setViewportSize({width:390,height:844});await reset();await go('orders/payment?id=AS-1001');
  await page.getByLabel('Simulated verified result').selectOption('Amount mismatch');await action('Verify existing payment');assert.equal((await state()).orders[0].items[0].stage,0);
  await page.getByLabel('Simulated verified result').selectOption('Captured');await action('Verify existing payment');await action('Verify existing payment');assert.equal((await state()).messages.filter(m=>m.order==='AS-1001'&&m.kind==='Order confirmation').length,1);
  await go('orders/job?id=AS-1001');await action('Check readiness & reserve');await page.locator('dialog').getByRole('checkbox').check();await confirm('Reserve & release');assert.equal((await state()).orders[0].items[0].stage,2);
  await action('Start printing');await page.locator('dialog').getByRole('checkbox').check();await confirm('Start printing');assert.equal((await state()).orders[0].items[0].stage,3);
  await action('Printing complete · move to framing');await page.locator('dialog').getByRole('checkbox').check();await confirm('Move to framing');
  await go('orders/quality?id=AS-1001');for(const c of await page.locator('main input[type=checkbox]').all())await c.check();await page.getByLabel('Inspection evidence',{exact:true}).selectOption('Sample photo reference — synthetic');await action('Record inspection');assert.equal((await state()).orders[0].items[0].stage,5);
  await go('orders/packing?id=AS-1001');for(const c of await page.locator('main input[type=checkbox]').all())await c.check();for(const [name,value] of [['Actual weight (kg)','4.2'],['Length (cm)','72'],['Width (cm)','54'],['Height (cm)','9']])await page.getByLabel(name,{exact:true}).fill(value);await page.getByLabel('Parcel evidence',{exact:true}).selectOption('Sample photo reference — synthetic');await action('Save packing & create parcel');await page.waitForURL('**#orders/parcel?id=AS-1001&item=LI-1');
  await page.getByLabel('Serviceability checked for the current address').check();await page.getByLabel('Simulated booking response').selectOption('Unknown');await action('Create sample booking');assert.equal((await state()).orders[0].items[0].stage,6);await action('Check existing Shiprocket booking');await page.locator('dialog').getByRole('checkbox').check();await confirm('Link existing booking');assert.equal((await state()).orders[0].items[0].stage,7);
  await page.getByLabel('Physical collection evidence / pickup reference').fill('PICKUP-DEMO-001 / collected by sample courier');await action('Record physical handover');assert.equal((await state()).orders[0].items[0].stage,8);
  await page.getByLabel('Simulated verified courier event').selectOption('Delivered');await action('Record courier event');assert.equal((await state()).orders[0].items[0].stage,10);await page.getByLabel('Simulated verified courier event').selectOption('Out for delivery');await action('Record courier event');assert.equal((await state()).orders[0].items[0].stage,10);
  assert.deepEqual((await state()).messages.filter(m=>m.order==='AS-1001').map(m=>m.kind),['Order confirmation','Production started','Dispatched','Delivered']);await page.reload();assert.equal((await state()).orders[0].items[0].stage,10);
  result.checks.push('Phone: complete payment-to-delivery journey, mismatch blocking, duplicate payment, one booking after timeout, handover before dispatch, stale delivery event, four messages and refresh persistence.');
  await go('orders/all');await page.getByLabel('Search orders',{exact:true}).fill('Meera');assert.equal(await page.locator('#order-count').textContent(),'1 matching orders');await page.getByRole('link',{name:'Open order',exact:true}).click();await page.getByRole('link',{name:'← Back to retained order view',exact:true}).click();assert.equal(await page.getByLabel('Search orders',{exact:true}).inputValue(),'Meera');await page.getByLabel('Search orders',{exact:true}).fill('does-not-exist');assert(await page.getByRole('heading',{name:'No matching orders'}).isVisible());await action('Clear filters');
  await page.locator('#record-search').fill('AWB-DEMO-1003-1');await page.locator('#global-search button').click();await page.getByRole('link',{name:'Open original record',exact:true}).click();assert.equal(await page.locator('h1').textContent(),'Parcel PAR-1003-1');
  result.checks.push('Retained order filters, no-match recovery and global provider-reference search open original records.');
  await go('settings/journeys');for(let n=1;n<=23;n++){await page.selectOption('#role-select','owner');await go('settings/journeys?story='+n);await action('Load this scenario');await confirm('Load review scenario');await page.waitForFunction(n=>AdminStore.state.scenario===n,n);assert(!['Record unavailable','Page not found'].includes(await page.locator('h1').textContent()),'Story '+n);if(n===20)assert.equal(await page.locator('h1').textContent(),'Access restricted');}
  result.checks.push('All 23 AF1 story loaders restore a fresh scenario, including Operations direct-finance denial.');
  await reset();await go('orders/quality?id=AS-1006');for(const c of await page.locator('main input[type=checkbox]').all())await c.check();await page.getByLabel('Inspection evidence',{exact:true}).selectOption('Sample photo reference — synthetic');await action('Record inspection');assert((await page.locator('main [role=alert]').textContent()).includes('rework'));await action('Record correction & recheck');await page.locator('dialog').getByLabel('Correction and materials used').fill('Marked corner replaced; original pinned file retained.');await confirm('Ready for reinspection');for(const c of await page.locator('main input[type=checkbox]').all())await c.check();await page.getByLabel('Inspection evidence',{exact:true}).selectOption('Sample photo reference — synthetic');await action('Record inspection');assert.equal((await state()).orders[5].items[0].quality,'Passed');assert.equal((await state()).orders[5].items[0].inspections.length,2);
  await go('orders/refund?id=AS-1004');await page.getByLabel('Affected quantity').fill('1');await page.getByLabel('Refund amount (INR)').fill('1000');await page.getByLabel('Reason and scope').fill('Partial sample remedy for the affected frame.');await action('Create refund request');await page.locator('button[data-action=refund-approve]').last().click();await page.locator('dialog').getByRole('checkbox').check();await confirm('Approve current amount');await page.locator('button[data-action=refund-submit]').click();await page.locator('dialog').getByLabel('Simulated submission response').selectOption('Unknown');await confirm('Submit simulation');assert.equal((await state()).orders[3].refunds.at(-1).status,'Unknown');await page.locator('button[data-action=refund-verify]').last().click();await page.locator('dialog').getByLabel('Simulated verified outcome').selectOption('Completed');await confirm('Record verified result');assert.equal((await state()).orders[3].refunds.at(-1).status,'Completed');
  result.checks.push('Failed inspection cannot pass without recorded correction; history survives recheck. Partial refund approval, unknown submission and confirmed recovery work.');
  await go('support/case?id=CS-1002');await action('Use saved reply');await page.locator('dialog').getByLabel('Actual sample outcome').selectOption('Manually sent through original channel');await confirm('Record reply outcome');assert((await page.locator('#modal-error').textContent()).includes('identity'));await page.locator('dialog').getByRole('checkbox').check();await confirm('Record reply outcome');assert.equal((await state()).cases[1].replies.length,1);
  await go('products/import');await action('Load mixed sample rows');assert.equal((await state()).importRows.filter(r=>r.error).length,5);await action('Apply valid rows');await confirm('Apply valid drafts');assert.equal((await state()).products[0].status,'Draft');assert.equal((await state()).products.at(-1).id,'NEW-DEMO-1');
  await go('products/artwork?id=NEW-DEMO-1');await action('Review publication');await confirm('Publish locally');assert((await page.locator('#modal-error').textContent()).includes('Rights'));await page.locator('dialog [data-close]').first().click();
  await go('settings/access');await action('Preview sign-out');await confirm('End demo session');await page.getByLabel('Sample two-factor code').fill('123456');await action('Open sample session');assert.equal((await state()).signedIn,true);
  result.checks.push('Identity-gated manual support response, CSV row errors/drafts, incomplete-publication block and synthetic two-factor session journey.');
  await reset();await go('orders/all');const beforeSkip=page.url();await page.locator('.skip').focus();await page.keyboard.press('Enter');assert.equal(page.url(),beforeSkip);assert.equal(await page.evaluate(()=>document.activeElement.id),'main');
  assert(await page.locator('#sidebar').evaluate(el=>el.inert));await page.locator('#menu-toggle').click();assert(await page.locator('#sidebar').evaluate(el=>!el.inert&&el.contains(document.activeElement)));await page.keyboard.press('Escape');assert(await page.locator('#sidebar').evaluate(el=>el.inert));assert.equal(await page.evaluate(()=>document.activeElement.id),'menu-toggle');await page.setViewportSize({width:1440,height:900});await page.waitForFunction(()=>!document.querySelector('#sidebar').inert);await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('#sidebar').inert);
  result.checks.push('Keyboard: skip link preserves route and focuses content; closed phone navigation is inert, opening moves focus, Escape restores it and desktop resize restores navigation access.');
  await go('support');await action('Capture a request');await page.locator('dialog').getByLabel('New enquiry contact name',{exact:true}).fill('Review Enquirer');await page.locator('dialog').getByLabel('New enquiry contact email',{exact:true}).fill('enquirer@example.test');await page.locator('dialog').getByLabel('Subject',{exact:true}).fill('Artwork availability before ordering');await page.locator('dialog').getByLabel('Customer request',{exact:true}).fill('Please confirm the current A2 finishes.');await confirm('Create request');const enquiry=(await state()).cases.at(-1);assert.equal(enquiry.order,null);assert((await state()).tasks.some(t=>t.record===enquiry.id&&t.owner===enquiry.owner));await go('support/case?id='+enquiry.id);assert.equal(await page.locator('h1').textContent(),'Artwork availability before ordering');assert(await page.getByText('Pre-purchase enquiry',{exact:true}).isVisible());await go('customers/profile?id='+enquiry.customer);assert.equal(await page.locator('h1').textContent(),'Review Enquirer');
  result.checks.push('A pre-purchase enquiry creates a separate contact and owned case without inventing an order; original profile/case links open correctly.');
  await go('orders/document?id=AS-1004');await action('Prepare sample document');await page.locator('dialog').getByLabel('Document type').selectOption('Credit note');await confirm('Issue sample');assert.equal((await state()).orders[3].documents.length,1);assert.equal((await state()).orders[3].documents[0].amount,200000);await action('Prepare sample document');await page.locator('dialog').getByLabel('Document type').selectOption('Credit note');await confirm('Issue sample');assert((await page.locator('#modal-error').textContent()).includes('No confirmed refund'));assert.equal((await state()).orders[3].documents.length,1);await page.locator('dialog [data-close]').first().click();
  await go('support/return?id=CS-1004');await page.getByLabel('Return event').selectOption('Inspected — recoverable');await page.getByLabel('Physical evidence / inspection and reason').fill('Synthetic physical evidence');await action('Record return event');assert((await page.locator('main [role=alert]').textContent()).includes('actual studio receipt'));for(const event of ['Pickup requested','In return transit','Received at studio','Inspected — recoverable']){await page.getByLabel('Return event').selectOption(event);await page.getByLabel('Physical evidence / inspection and reason').fill('Synthetic evidence for '+event);await action('Record return event');}await page.getByLabel('Return event').selectOption('Pickup requested');await page.getByLabel('Physical evidence / inspection and reason').fill('Old pickup event');await action('Record return event');assert((await page.locator('main [role=alert]').textContent()).includes('earlier or repeated'));assert.equal((await state()).cases[0].claim.returnStatus,'Inspected — recoverable');assert.equal((await state()).cases[0].claim.returnHistory.length,4);
  result.checks.push('Confirmed refund value is credited once; return inspection requires actual receipt and old events cannot erase the four-event movement/evidence history.');
  await page.evaluate(()=>{AdminStore.mutate('REPLIES','Review draft-only library',()=>AdminStore.state.savedReplies.forEach(r=>r.status='Draft'));});await go('support/case?id=CS-1002');await action('Use saved reply');assert.equal(await page.locator('#dialog-title').textContent(),'No approved saved reply');await confirm('Review reply library');assert.equal(await page.locator('h1').textContent(),'Saved replies');
  await go('orders/all');const other=await page.context().newPage();await other.goto(base+'#orders/all');await other.evaluate(()=>AdminStore.mutate('AS-1001','Other tab note',()=>AdminStore.order('AS-1001').note='Retain the newer tab note'));await page.getByLabel('Search orders',{exact:true}).fill('Meera');assert((await page.locator('#toast').textContent()).includes('another tab'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(AdminStore.KEY)).orders[0].note),'Retain the newer tab note');await other.close();await page.reload();
  result.checks.push('An all-draft reply library has an actionable approval state; changing order filters in a stale tab cannot overwrite newer work.');
  assert.equal(await page.evaluate(()=>localStorage.getItem('public-cart-sentinel')),'unchanged');assert.equal(await page.evaluate(()=>sessionStorage.getItem('public-session-sentinel')),'unchanged');assert.deepEqual(result.errors,[]);
  result.checks.push('No business/provider requests, no public storage changes; sample state only.');fs.writeFileSync(out+'/review.json',JSON.stringify(result,null,2));console.log(JSON.stringify({screens:routes.length,viewportChecks:result.routes.length,captures:result.captures.length,checks:result.checks},null,2));
 }catch(e){result.failure=e.stack;fs.writeFileSync(out+'/review.json',JSON.stringify(result,null,2));throw e;}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
